#version 450
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_16bit_storage : require

layout(local_size_x = 2) in;
layout(buffer_reference, std430, buffer_reference_align = 16) buffer Bytes {
    uint8_t values[2];
    uint16_t short_value;
};
layout(push_constant) uniform Push {
    layout(offset = 0) uint64_t delta;
    layout(offset = 8) uint64_t root;
} pc;

void main() {
    Bytes bytes = Bytes(pc.root + pc.delta);
    uint i = gl_LocalInvocationIndex;
    bytes.values[i] = uint8_t(0x31 + i);
    if (i == 0) {
        bytes.short_value = uint16_t(0x4567);
    }
}
